# Generated by Django 4.0.4 on 2022-05-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_remove_contract_projectcomponents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='adminApproval',
            field=models.BooleanField(default=False),
        ),
    ]
